name: End-to-end tests 🧪
on:
  push:
  schedule:
    - cron: '30/5 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress run
        uses: cypress-io/github-action@v4